### ISSUE TITLE
Broken Supplementary Material link

### ISSUE THREAD

**Issue by madhavaggar** [allenai/satlas#10]
Hi, I have been trying to access the supplementary material but the link seems to be broken.

**Comment by favyen2** [comment]
Which link are you using and what page do you see it on? I am able to load it here:

https://pub-956f3eb0f5974f37b9228e0a62f449bf.r2.dev/SatlasPretrain_supplementary.pdf

**Comment by madhavaggar** [comment]
https://pub-956f3eb0f5974f37b9228e0a62f449bf.r2.dev/SatlasPretrain_supplementary.pdf. This doesn't work for me.

**Comment by favyen2** [comment]
What do you see when you open it?

**Comment by madhavaggar** [comment]
It fails to load.
<img width="674" alt="Screenshot 2023-09-07 at 5 34 52 PM" src="https://github.com/allenai/satlas/assets/49604066/7c8391c1-1768-4754-aed0-13a0c3b9e004">

**Comment by favyen2** [comment]
This is a Cloudflare URL so it is strange that it times out for you. What ISP are you accessing from?

**Comment by madhavaggar** [comment]
University Eduroam

**Comment by favyen2** [comment]
Please contact your ISP to investigate the issue accessing this Cloudflare URL.

**Comment by louisguitton** [comment]
> University Eduroam

@madhavaggar Universities use Eduroam to "secure" internet access. Most likely, your uni has put firewalls in place that prevent you from accessing that URL.
Try to access that URL from another wifi connection, for example in tethering from your phone's data plan.
