### ISSUE TITLE
Request very small sample

### ISSUE THREAD

**Issue by robmarkcole** [allenai/satlas#11]
The sample `Small versions of the NAIP and Sentinel-2 images are available` are close to 600GB as far as I can tell, and are too large for my machine to download. Can I request a very small sample, closer to 0.6GB? Many thanks

**Comment by favyen2** [comment]
We don't want to maintain another download, but SatlasPretrain consists of tar files so you could download them partially to whatever point you like and then untar (with `tar xvf`), and it should successfully extract a bunch of files until it gets to the end and exits with error.
