### ISSUE TITLE
Please make all models available as standalone download

### ISSUE THREAD

**Issue by robmarkcole** [allenai/satlas#12]
I would like to tryout [models/solar_farm/best.pth](https://pub-956f3eb0f5974f37b9228e0a62f449bf.r2.dev/satlas_explorer_datasets/satlas_explorer_datasets_2023-07-24.tar) which downloads `satlas_explorer_datasets_2023-07-24.tar` which is > 900GB. Please could you make the model available as a standalone download
Thanks

**Comment by favyen2** [comment]
Added a separate 1.5 GB download with just the model weights:

https://pub-956f3eb0f5974f37b9228e0a62f449bf.r2.dev/satlas_explorer_datasets/satlas_explorer_datasets_modelsonly_2023-07-24.tar

Thanks for the feedback!

Edit: sorry the first 2.8 GB download was incorrect, it should be a 1.5 GB download.
