### ISSUE TITLE
Minor improvements in Sentinel-2 Inference Example

### ISSUE THREAD

**Issue by robmarkcole** [allenai/satlas#14]
Following https://github.com/allenai/satlas/issues/13 I note a couple of minor improvements

* `from osgeo import gdal` is not required for this example and can be removed (somehow this always gives headaches on mac)
* `device = torch.device("cuda")` -> preferable to use `device = torch.device("cuda" if torch.cuda.is_available() else "cpu")` to avoid errors on CPU

**Comment by favyen2** [comment]
Thanks, made these changes (updated the device in the other scripts as well)
