### ISSUE TITLE
Self supervised results

### ISSUE THREAD

**Issue by robmarkcole** [allenai/satlas#17]
Per the text below, I am looking for supplementary B.3 but cannot locate it. Can you advise? 
Thanks

<img width="335" alt="image" src="https://github.com/allenai/satlas/assets/11855322/7693e668-ef06-4b8b-b889-bbd2841a2d39">

**Comment by favyen2** [comment]
The supplementary material is at https://pub-956f3eb0f5974f37b9228e0a62f449bf.r2.dev/SatlasPretrain_supplementary.pdf

B.3 is on page 16 while the table is on page 20.
