### ISSUE TITLE
No json file

### ISSUE THREAD

**Issue by HuangShiqi128** [allenai/satlas#18]
Hi,

I couldn't find 

Additional` files in satlas/metadata/ contain extra data. train_highres.json, train_lowres.json, test_event.json, test_highres.json, train_lowres.json, test_event.json enumerate the tiles assigned to each split.

May I ask where it is?

**Comment by favyen2** [comment]
It should be in the dataset download (https://github.com/allenai/satlas/blob/main/SatlasPretrain.md#satlaspretrain-dataset) specifically the `satlas-dataset-v1-metadata.tar` file, do you not see it there?

**Comment by nilsleh** [comment]
Sorry to open this again @favyen2 , but I actually cannot find the metadata tarball on huggingface and I tried:

```
hf_hub_download(repo_id="allenai/satlas-pretrain", filename="satlas-dataset-v1-metadata.tar")
Entry Not Found for url: https://huggingface.co/allenai/satlas-pretrain/resolve/main/satlas-dataset-v1-metadata.tar.
```



and

```
hf_hub_download(repo_id="allenai/satlas-pretrain", filename="dataset/satlas-dataset-v1-metadata.tar")
Entry Not Found for url: https://huggingface.co/allenai/satlas-pretrain/resolve/main/dataset/satlas-dataset-v1-metadata.tar.
```

**Comment by favyen2** [comment]
Here it is https://huggingface.co/allenai/satlas-pretrain/blob/main/dataset/satlaspretrain_dataset_metadata_0000.tar

You can also use the URLs here https://github.com/allenai/satlas/blob/main/satlaspretrain_urls.txt
