### ISSUE TITLE
Any plans to support change detection?

### ISSUE THREAD

**Issue by robmarkcole** [allenai/satlas#19]
Could be using a Unet at the most basic, or any number of other dedicated change detection networks

**Comment by favyen2** [comment]
We have some ongoing change detection related projects, but don't plan to incorporate it into this codebase.

We have not conducted thorough experiments on the downstream performance of SatlasPretrain models for change detection tasks, but from testing on a few datasets (like Onera Satellite Change Detection Dataset) the performance was comparable to [CACo](https://openaccess.thecvf.com/content/CVPR2023/papers/Mall_Change-Aware_Sampling_and_Contrastive_Learning_for_Satellite_Images_CVPR_2023_paper.pdf), and both outperformed the other models we tested.

So loading SatlasPretrain weights, applying them independently on different satellite images, and then concatenating the features for bitemporal or running some kind of 3D UNet or Conv-LSTM on one of the 2D feature maps, may work well.
