### ISSUE TITLE
where can I find the segmentation label ids?

### ISSUE THREAD

**Issue by yan-hao-tian** [allenai/satlas#21]
🥹

**Comment by favyen2** [comment]
For SatlasPretrain, the labels are contained in the "labels-dynamic" and "labels-static" downloads at https://github.com/allenai/satlas/blob/main/SatlasPretrain.md#download

https://github.com/allenai/satlas/blob/main/SatlasPretrain.md#labels has examples of labels including polygons which correspond to instance segmentation task.

For the fine-tuning datasets, only solar farms involves semantic segmentation, those labels are here: https://github.com/allenai/satlas#task-specific-labels-and-model-weights
