### ISSUE TITLE
Are Sentinel-2 in the dataset atmospherically corrected?

### ISSUE THREAD

**Issue by ghost** [allenai/satlas#24]
Dear favyen2:
I am reaching out to seek clarification regarding the Sentinel-2 dataset, specifically with regards to the inclusion of the "L1C" designation in the naming convention. I am genuinely interested to understand whether these satellite images are indeed classified under the L1C product level and whether they have undergone any significant atmospheric correction procedures.

Recognizing the pivotal role of accurate atmospheric correction in remote sensing applications, I am eager to ascertain whether the Sentinel-2 data labeled as L1C has been subjected to specific atmospheric correction operations aimed at enhancing its quality and reliability.

**Comment by favyen2** [comment]
The Sentinel-2 images are derived from Level-1C products as detailed here: https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-2-msi/product-types/level-1c

The only processing is projecting to Web-Mercator / gridding, and re-normalizing the intensities as 0-255 for storage as 8-bit PNGs (https://github.com/allenai/satlas/blob/main/Normalization.md#sentinel-2-images).
