### ISSUE TITLE
Cannot download pretrained models

### ISSUE THREAD

**Issue by ShreelekhaR** [allenai/satlas#28]
hi! I was hoping to try some stuff our with the resnet50 model for single rgb images but could not download it using either the link or wget. Will these links be updated soon?

**Comment by favyen2** [comment]
What error do you get when downloading from https://pub-956f3eb0f5974f37b9228e0a62f449bf.r2.dev/satlaspretrain/sentinel2/si_sb_resnet50.pth ?

**Comment by akgupta5592** [comment]
(env) (base) Anils-MacBook-Pro:penpotfest_workshop anilkumargupta$ python3 download_models.py
Downloading embeddings model all-MiniLM-L6-v2 into models
Embeddings model downloaded and ready!
Downloading LLM model ggml-gpt4all-j-v1.3-groovy into models
Traceback (most recent call last):
  File "/Users/anilkumargupta/penpotfest_workshop/download_models.py", line 30, in <module>
    main()
  File "/Users/anilkumargupta/penpotfest_workshop/download_models.py", line 25, in main
    GPT4All(model=f'./{models_directory}/{llm_model_name}', allow_download=True)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for GPT4All
__root__
  Model filename not in model list: ggml-gpt4all-j-v1.3-groovy.bin (type=value_error)
(env) (base) Anils-MacBook-Pro:penpotfest_workshop anilkumargupta$

**Comment by ShreelekhaR** [comment]
Saw this late! Download link worked thanks
