### ISSUE TITLE
How to improve the speed of dataset downloading

### ISSUE THREAD

**Issue by senlinxiaolangtaba** [allenai/satlas#3]
Hello, I'm very interested in the dataset you have released and would like to use it for some research. However, I've noticed that the download speed is currently very slow, averaging around 100 kb/s. Is there a faster way to download the dataset or an alternative download channel with higher speed? Thank you very much!

**Comment by senlinxiaolangtaba** [comment]
I noticed that you provide a small version of the dataset, but I couldn't find the corresponding labels. Could you please provide the labels for the small version?

**Comment by favyen2** [comment]
You would need to download the small image sets in conjunction with the full label and metadata sets. The datasets are served from S3 bucket so we do not have control over its performance, and we don't have resources to release an alternative download in multi-region.
