### ISSUE TITLE
can the fine tune models also be uploaded to huggingface?

### ISSUE THREAD

**Issue by rbavery** [allenai/satlas#34]
thanks for publishing the pretrained models! https://huggingface.co/allenai/satlas-pretrain

can the finetune models be uploaded individually as well?

currently all fine-tunes needs to be downloaded and untar-ed at once: https://pub-956f3eb0f5974f37b9228e0a62f449bf.r2.dev/satlas_explorer_datasets/satlas_explorer_datasets_2023-07-24.tar

**Comment by favyen2** [comment]
OK they are now available on huggingface here:

https://huggingface.co/allenai/satlas-pretrain/tree/main/finetuned_satlas_explorer_models_2023-07-24

See bottom of [SatlasPretrain.md](https://github.com/allenai/satlas/blob/main/SatlasPretrain.md#visualizing-outputs-on-new-images) for how to apply these models.
