### ISSUE TITLE
why does the marine infra dataset contain extra TCI images when the config specifies 3 time steps are used?

### ISSUE THREAD

**Issue by rbavery** [allenai/satlas#36]
Thanks again for all the great work on satlas! I have a question about the marine infra dataset.

I think this indicates the tci, tci0, and tci1 files are used for training

https://github.com/allenai/satlas/blob/f6786faf15c3b2d365d79955f33b3390ca1d673a/configs/satlas_explorer_marine_infrastructure.txt#L2

https://github.com/allenai/satlas/blob/f6786faf15c3b2d365d79955f33b3390ca1d673a/configs/satlas_explorer_marine_infrastructure.txt#L38

but the v1 dataset marine infra dataset contains 5 tci files.

```
satlas-dataset-marine-infrastructure-v1/1302_2844_f0d695513b9e44ea873e2a1cecce6f3f
├── gt.json
└── images
    └── f0d695513b9e44ea873e2a1cecce6f3f
        ├── tci.png
        ├── virtual:overlap_tci_0.png
        ├── virtual:overlap_tci_1.png
        ├── virtual:overlap_tci_2.png
        └── virtual:overlap_tci_3.png


```

are the other two tci files used in training or inference?

**Comment by favyen2** [comment]
We started with five images for annotation but then we ended up targeting the annotations towards the first three images in the time series and trained using those same images. Many later annotations only used three images.

So it is correct that the other two are not used in training. And during inference only input the latest three images at each location.

**Comment by rbavery** [comment]
got it, thank you!
