### ISSUE TITLE
Erratic Image Segmentation and Interpretation of Polygons

### ISSUE THREAD

**Issue by jayshrivastava0** [allenai/satlas#38]
We are applying the Pretrained satlas model **sentinel2_resnet50_mi_ms.pth** with the [corresponding config file](https://github.com/allenai/satlas/blob/main/configs/sentinel2/resnet50_mi_ms.txt) on a set of 8 sentinel2 images stacked together in (N*C, H, W) shape [(see attached RGB visualization)](https://drive.google.com/file/d/1jN-4OcgeaCdWID6SAuLvkRhbNXCV6UAa/view?usp=sharing) to do image segmentation. The output from the given template [custom inference code](https://github.com/allenai/satlas/blob/main/CustomInference.md?plain=1#L153) produces the following output:
[Output Image](https://drive.google.com/file/d/1o8Cdb_VbIgOSgTHTJrbjSomr9TR0BpsI/view?usp=sharing)
It is not clear where this large black area stems from. 
Based on the choice of the crop size paramter, the size of black area changes, but not as expected. Is this area being segmented as [unknown](https://github.com/allenai/satlas/blob/main/satlas/model/dataset.py#L104)?
So we tried some different values for crop size
[Output Image with crop size = 512](https://drive.google.com/file/d/1YGwEw1zYLF0O2Jp6oLkE6HwK0jlkZ2SQ/view?usp=sharing)
We also tried experimenting with crop size (2000) that is more than the size of input image. Expecting it to throw an error.
[Output Image with crop size = 2000](https://drive.google.com/file/d/1FLy1h3V-_NLkoXQVffQYjJdpx1-8ptud/view?usp=sharing)

>This led us to look deeper at the custom inference code and it seems that the crop size is actually the window size upon which various operation are performed. And not the actual cropping size of the input image. Is that the case?

### ***What is the relationship between the size of the input image and the crop-size parameter?***
Because we believe this crop size parameter is causing this large black area. If you think that is not the case can you please point us where this large black area might be coming from.

One another question..
How can one interpret the colored polygons? The file 'dataset.py' has the same color codes for different land cover types. For example in [crop_type there is [0, 0, 255], # (blue) rice](https://github.com/allenai/satlas/blob/main/satlas/model/dataset.py#L133) and [land_cover there is [0, 0, 255], # (blue) water](https://github.com/allenai/satlas/blob/main/satlas/model/dataset.py#L105).

**Comment by favyen2** [comment]
The crop size just determines the size of the crops/patches passed to the model. If it is smaller, then the image is divided into more smaller crops/patches, and if it is bigger, then the image is divided into fewer larger crops/patches. But either way the entire image should be processed.

I wasn't able to replicate the issue where most of the output is black. Which head are you using (controlled by `head_idx` in the inference code).

Regarding the colors, the duplicate blue color you mentioned come from different heads. The output visualization created by the example custom inference code only shows the outputs for one head. So you should look in the section of the configuration file or dataset.py that corresponds to the head/task you're running.

If you clarify the `head_idx` you're using and provide the .npy input then I can check further.

**Comment by jayshrivastava0** [comment]
We appreciate your prompt reply to this matter, Favyen. 

We are using ```head_idx = 0```. This is our [npy file](https://drive.google.com/file/d/15Mt_Vs1OAii3OamED3Zie3BKPtzNPMGY/view?usp=sharing) that we are using.
We also tried to run the inference while changing the ```head_idx``` and ```crop_size```. We are still getting the black region.

Thank you for clarifying the confusion on color.

**Comment by favyen2** [comment]
I'm not able to reproduce the issue with this numpy file where the output only appears on one side of the image.

I do see issue where, because the size is not a multiple of 32, it can run into errors for some of the heads. But if I crop it to e.g. 1024x1024 then it does not have a problem.

Here is example output with head_idx=2 (this is the land cover output that you had mentioned).

![rgb](https://github.com/allenai/satlas/assets/90410805/dac21bef-2b54-449f-98e3-afcffe76a882)
![output](https://github.com/allenai/satlas/assets/90410805/e7ba33c0-f53a-408b-bd7f-2b780f11148c)

**Comment by jayshrivastava0** [comment]
Thank you Favyen. We are now able to reproduce the output as well.
