### ISSUE TITLE
Missing satlas.util.mercator_to_geo() function

### ISSUE THREAD

**Issue by ando-shah** [allenai/satlas#40]
The Satlas pretrain [readme](https://github.com/allenai/satlas/blob/main/SatlasPretrain.md) file has the following reference:

`import satlas.util`
`satlas.util.mercator_to_geo((1867, 3287), pixels=1, zoom=13)`

The function `util.mercator_to_geo()` is missing, and would be useful to include.

**Comment by favyen2** [comment]
It is here:

https://github.com/allenai/satlas/blob/main/satlas/util/__init__.py

What error do you get?

**Comment by ando-shah** [comment]
Thanks - something was broken in my repo. Apologies!
