### ISSUE TITLE
Aligned data on US subsection of SatlasPretrain

### ISSUE THREAD

**Issue by gastruc** [allenai/satlas#43]
Hi,
I am currently working on SatlasPretrain. Is there a way to determine which files to request to build the aligned S2/S1/NAIP dataset across the US without unzipping the entire dataset? I would like to determine how to build the multi modal dataset like in [this work]()https://arxiv.org/abs/2312.02199).

**Comment by favyen2** [comment]
You would need to unzip the entire dataset (or at least unzip NAIP and then selectively unzip the files in the other zip files that match with the NAIP tiles).

You might find this dataset useful: https://huggingface.co/datasets/allenai/s2-naip

We are working on dataset spanning continental US with NAIP, Sentinel-2, Sentinel-1, Landsat-8/9 (OLI/TIRS), OpenStreetMap, and WorldCover. Currently Sentinel-1 and Landsat-8/9 have not been uploaded yet, maybe next week for Sentinel-1.

**Comment by favyen2** [comment]
Sentinel-1 imagery for continental US aligned spatially and temporally with NAIP is now available at the aforementioned dataset: https://huggingface.co/datasets/allenai/s2-naip
