### ISSUE TITLE
Issues aboout the small version

### ISSUE THREAD

**Issue by moonboy12138** [allenai/satlas#45]
I noticed that you offer a smaller version of this dataset, available [here](https://github.com/allenai/satlas/blob/main/satlaspretrain_urls_small.txt). What are the differences between this small version and the original? Does the small version still provide global coverage, or is it just a subset of the original dataset?

**Comment by favyen2** [comment]
The small version is intended to just be a sample of the dataset to show the format. It is a small subset of the original dataset and does not provide global coverage.

You may also be interested in our dataset at https://huggingface.co/datasets/allenai/s2-naip with NAIP, Sentinel-2, Sentinel-1, Landsat, OpenStreetMap, and WorldCover at every location in the continental US.
