### ISSUE TITLE
Sentinel-1 acquisition/normalization details

### ISSUE THREAD

**Issue by ando-shah** [allenai/satlas#49]
The [normalization](https://github.com/allenai/satlas/blob/main/Normalization.md) page mentions the following for S-1:
"Each band is originally a 16-bit image. We normalize a pixel value N to 0-1 by clipping N/255 to 0-1 (any pixel values greater than 255 become 1)."

- Were these acquired from GEE using `S1_GRD_FLOAT` collection? If so those typically come in values from 0-1. If not, they should come in decibel scale, and are typically between 0 and -50. Any details here would be helpful

- Were these acquired using both ascending and descending orbits?

- Are the mean and standard deviation values of the S-1 dataset available?

Thanks!

**Comment by favyen2** [comment]
They are downloaded from ESA. Values are unsigned 16-bit integer, 0-65535, in the PNG they are clipped to 0-255. https://browser.dataspace.copernicus.eu/ (GRD IW VV+VH products) See https://documentation.dataspace.copernicus.eu/APIs/SentinelHub/Data/S1GRD.html#units for details.

It is both ascending and descending.

Not for the entire dataset but typical mean/std in Sentinel-1 scenes are mean 100 std 40.

**Comment by ando-shah** [comment]
Thanks - this is super helpful.

FYI mean/std for something like 10% (random) of the s-1 dataset is:
VV: 137/18
VH: 111/20
