### ISSUE TITLE
Clarification on Matching NAIP Images with Labels in Dataset

### ISSUE THREAD

**Issue by Amazingren** [allenai/satlas#50]
Dear team,

Thank you for sharing such an interesting dataset and work.

While exploring the dataset, I am focusing on using only the NAIP images and their corresponding labels. Specifically, I plan to work with the NAIP data from 2020 and its associated labels.

I noticed that the NAIP images are named in the format `xxxxx_xxxxx.png`, where `x` represents a number. However, when I downloaded the static labels (approximately 117GB), they were organized into folders, each named using the format `xxxx_xxxx`, without matching the exact file names of the NAIP images.

This lack of direct pairing between NAIP images and their labels—unlike what I observed with other data types like Sentinel-1 and Sentinel-2—has caused some confusion in aligning the data with the labels I want to use.

Could you please provide guidance on how to accurately match the labels with the NAIP images?

Thank you very much for your assistance.

Best regards,

**Comment by favyen2** [comment]
NAIP images are stored at zoom 17 instead of 13 (factor of 16 higher resolution) so 12345_67890.png would correspond to the crop from (288, 64) to (320, 96) in 771_4243.json (divide by 16 and round down to get the zoom 13 tile, and take modulo to get the index within the tile).

**Comment by Amazingren** [comment]
> NAIP images are stored at zoom 17 instead of 13 (factor of 16 higher resolution) so 12345_67890.png would correspond to the crop from (288, 64) to (320, 96) in 771_4243.json (divide by 16 and round down to get the zoom 13 tile, and take modulo to get the index within the tile).

Great! Thanks for your quick reply. Now I am clear about this.

Best regards and many thanks,

**Comment by Randomdude11** [comment]
A correction: once you get the modulo, you must multiply it by 512, not 32, to get the index within the tile. So instead of (288, 64) the coordinates inside that tile would be ((12345%16)*512, (67890%16)*512).
