### ISSUE TITLE
I cannot see Marine Infrastructure annotations after starting from this link

### ISSUE THREAD

**Issue by schmmd** [allenai/satlas#7]
https://satlas.allen.ai/map?state={%22view%22:{%22longitude%22:-121.86294560150702,%22latitude%22:47.74155600890629,%22zoom%22:6.862586335547447,%22pitch%22:0,%22bearing%22:0},%22showHeatmap%22:false,%22showAnimation%22:false,%22showSatellite%22:false,%22selectedDateOption%22:%222019-07%22,%22selectedDateOptionSecondary%22:%222022-06%22,%22selectedStartDateOption%22:%222017-01%22,%22selectedEndDateOption%22:%222022-01%22,%22selectedTreeCoverFill%22:[{%22label%22:%22None%22,%22isChecked%22:false},{%22label%22:%22Low%22,%22isChecked%22:false},{%22label%22:%22Medium%22,%22isChecked%22:true},{%22label%22:%22High%22,%22isChecked%22:true},{%22label%22:%22Full%22,%22isChecked%22:true}],%22selectedMarineInfra%22:[{%22label%22:%22Offshore%20Wind%20Turbines%22,%22isChecked%22:true},{%22label%22:%22Offshore%20Platforms%22,%22isChecked%22:false}],%22selectedRenewableEnergy%22:[{%22label%22:%22Solar%20Farms%22,%22isChecked%22:true},{%22label%22:%22Onshore%20Wind%20Turbines%22,%22isChecked%22:false}],%22selectedApplication%22:%22Marine%20Infrastructure%22,%22selectedLayout%22:%22Single%20Map%22}

I cannot see any offshore wind farm annotations, but I should be able to.

**Comment by favyen2** [comment]
Is that because the "Offshore Wind Turbines" and "Offshore Platforms" are unchecked?

**Comment by schmmd** [comment]
Sorry, got interrupted and accidentally submitted this before filling in all the details.  No, I don't think that's the issue because when I check "Offshore Wind Turbines" nothing shows up.  If I start from the base URL and then configure the same settings, I can see the annotations so I think this is a frontend issue.

**Comment by favyen2** [comment]
Moved to https://github.com/allenai/satlas-app/issues/199
