### ISSUE TITLE
Dataset Download links not working

### ISSUE THREAD

**Issue by srinify** [allenai/satlas#8]
Hi there -- I'm excited to explore these datasets but these links don't seem to be working:

https://github.com/allenai/satlas/blob/main/GeospatialDataProducts.md

- GeoJSON: https://pub-956f3eb0f5974f37b9228e0a62f449bf.r2.dev/outputs/marine/YYYY-MM.geojson
- KML: https://pub-956f3eb0f5974f37b9228e0a62f449bf.r2.dev/outputs/marine/YYYY-MM.kml
- Shapefile: https://pub-956f3eb0f5974f37b9228e0a62f449bf.r2.dev/outputs/marine/YYYY-MM.shp

I believe these buckets aren't set to public?

**Comment by favyen2** [comment]
Thanks for your interest in the data!

The YYYY-MM is a placeholder, so an example URL is
https://pub-956f3eb0f5974f37b9228e0a62f449bf.r2.dev/outputs/marine/2023-01.geojson

The index at
https://pub-956f3eb0f5974f37b9228e0a62f449bf.r2.dev/outputs/marine/index.txt
lists the currently available files.

We will look into updating the documentation to make this more clear.

**Comment by srinify** [comment]
Ah yes, I clearly didn't read the instructions well enough :)

For other people like me who browsed too fast ... it may be good to add a specific example I can copy & paste. Great work!

**Comment by favyen2** [comment]
I'll keep it open until the documentation is updated, thanks for the feedback about it.
