### ISSUE TITLE
Missing OpenStreetMap attribution in the map view

### ISSUE THREAD

**Issue by habi** [allenai/satlas#9]
As an OpenStreetMap contributor, I am pleased to see that you are using OpenStreetMap on the [map view](https://satlas.allen.ai/map?state={%22view%22:{%22longitude%22:7.434502096508794,%22latitude%22:46.87562088518925,%22zoom%22:9.697733223732834,%22pitch%22:0,%22bearing%22:0},%22showHeatmap%22:true,%22showAnimation%22:false,%22showSatellite%22:false,%22selectedDateOption%22:%222022-12%22,%22selectedDateOptionSecondary%22:%222016-01%22,%22selectedStartDateOption%22:%222016-01%22,%22selectedEndDateOption%22:%222022-12%22,%22selectedTreeCoverFill%22:[{%22label%22:%22None%22,%22isChecked%22:false},{%22label%22:%22Low%22,%22isChecked%22:false},{%22label%22:%22Medium%22,%22isChecked%22:true},{%22label%22:%22High%22,%22isChecked%22:true},{%22label%22:%22Full%22,%22isChecked%22:true}],%22selectedMarineInfra%22:[{%22label%22:%22Offshore%20Wind%20Turbines%22,%22isChecked%22:true},{%22label%22:%22Offshore%20Platforms%22,%22isChecked%22:false}],%22selectedRenewableEnergy%22:[{%22label%22:%22Solar%20Farms%22,%22isChecked%22:true},{%22label%22:%22Onshore%20Wind%20Turbines%22,%22isChecked%22:true}],%22selectedApplication%22:%22Super%20Resolution%22,%22selectedLayout%22:%22Single%20Map%22}) (turn off "Super Res View").

However, I noticed that the map seems to lack the proper credit. OpenStreetMap's license requires that you both credit OpenStreetMap and make users aware of the data license (by linking to our copyright page). For more information, see: https://www.openstreetmap.org/copyright

The correct attribution helps to avoid misunderstandings about the source of the map or data, as well as what others are allowed to do with it. If you need help making the changes or have further questions, feel free to ask in one of OpenStreetMap's communication channels: https://wiki.openstreetmap.org/wiki/Contact

**Comment by tastrax** [comment]
https://docs.mapbox.com/help/getting-started/attribution/

**Comment by favyen2** [comment]
Thanks, this has been fixed (thanks @arnavic)
